test: test cases added for hooks and precommit hook added for coverage report

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,15 +2,16 @@
 . "$(dirname "$0")/_/husky.sh"
 
 npm run format
-npm run lint:fix
+npm run lint
+npm run test:coverage
+RESULT=$?
+if [ $RESULT -ne 0 ]; then
+  echo "Pre-commit failed: Formatting, linting, or test coverage errors found."
+  exit 1
+fi
 
 # Re-stage all changes after fixing
 git add .
 
 # Optionally, run lint again to ensure no errors remain
-npm run lint
-RESULT=$?
-if [ $RESULT -ne 0 ]; then
-  echo "Pre-commit failed: Formatting or linting errors found."
-  exit 1
-fi
+# npm run lint
